name: subway
description: MJU subway team project1
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.3
  excel: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  material_floating_search_bar_2: ^0.5.0
  photo_view: ^0.14.0
  dijkstra: ^0.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/map.jpg
    - lib/assets/images/map.png
    - lib/assets/images/MyWay.png
    - lib/data/stations.xlsx
    - lib/data/congestion.xlsx


  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: lib/assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900
